### ISSUE TITLE
[Mirror Request] ius

### ISSUE THREAD

**Issue by skyline-pro** [ZJUSCT/mirror-issues#13]
see https://mirrors.tuna.tsinghua.edu.cn/ius/ for details.

**Comment by RalXYZ** [comment]
Hi, `ius` mirror has been deployed.  See https://mirrors.zju.edu.cn/ius/
Meanwhile, there is no Chinese documentation available for the IUS mirror. Could you please help us write a document?

https://ius.io/setup
I saw this official document, but I think directly translating and copying it over may lead to some potential accuracy issues. Can you perform some modification of the official document during your setup process, so that it can be directly placed on the ZJU Mirror IUS documentation page?

If you would like to do this job, please put the doc file here: https://github.com/ZJUSCT/mirror-front/tree/main/docs/zh
And make a pull request in: https://github.com/ZJUSCT/mirror-front/pulls

**Comment by skyline-pro** [comment]
>
非常感谢您的帮助

但这台服务器以前是我师兄在维护，他毕业了之后交给了我，然后更新的时候发现缺了ZJU源没有这个

我可以提供如何换源的参考，但是安装部分我无法保证正确性
